# Spring配置
spring:
  profiles:
    include:
      prod-datasource,prod-redis
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# 项目相关配置
wwl:
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/wwl/uploadPath，Linux配置 /home/wwl/uploadPath）
  profile: ./wwl/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: char
  #版本号
  version: 1.0
  name: wwl后台管理
  copyrightYear: 2021-2099

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为7500
  port: 7500
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.wwl: debug
    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatisPlus配置
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 自定义TypeHandler
  type-handlers-package: com.wwl.framework.config.typehandler
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wwl.**.domain,com.wwl.**.entity
  global-config:
    #是否控制台
    banner: false
    db-config:
      #主键类型
      id-type: auto

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /prod-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

wx:
  # 公众号配置
  mp:
    configs:
      - appId: wxce78b06b677771b3
        secret: 9434269268e9113a8e9aaad87bfa912e
        token: xxxxxxxxxx
        aesKey: xxxxxxxxxxxxxxxxxxxx
  # 小程序配置
  ma:
    configs:
      - appId: wxce78b06b677771b3
        secret: 9434269268e9113a8e9aaad87bfa912e
        # 微信支付商户号，请去微信支付平台申请
        mchId: 1588227511
        # 微信支付商户密钥，请去微信支付平台申请
        mchKey: xxxxxxxxxxxxxxxxxxxxx

mall:
  # 支付、物流回调地址，即后台服务7500端口的外网访问域名，要保证外网能访问
  notify-host: http://xx.xxxx.com